sha2_all: sha2 sha2_more

# Doesn't crash, but likely _not_ working and just spinning its wheels.
sha2:
	lua top_in_client.lua "merkle.test.sha2"

#(idem)
sha2_more:
	lua top_in_client.lua "merkle.test.sha2_more"

# Looks like this works
complex:
	lua top_in_client.lua "alt_require.test.toys.complex"
